version: '3.8'
services:
  web:
    build: .
    ports:
      - '8025:8000'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/db_yugoff_blog
    depends_on:
      db:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_yugoff_blog
    ports:
      - '54321:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
